
var workData = [

	{"JobTitle":"Student Research","Company":"NSERC USRA program","Duration":"May 2023 - Current","Summary":"- Currently learning the necessary theory and tools needed to study minimal surfaces","Image":"/assets/nserclogo.png","ExpType":"mathematics","Skills":["Research","Manifolds","Calculus of Variation","Riemannian Geometry","Minimal Surfaces"]},
	
	{"JobTitle":"Full Stack Developer Co-op","Company":"SS&C Technologies","Duration":"May 2022 - Dec 2022","Summary":"•\tCreated and optimized SSIS packages in the company Data Warehouse for extraction, loading, and transformation (ETL) of SQL data, ultimately reduced package run time on servers by factor of 3\n•\tCreated webpages using REST APIs and React components to handle client billing, data entry and pdf report generation while coding detailed business logic into the interface, maintained security through access permissions and kept audit trails as required by financial institutions\n","Image":"/assets/ssnclogo.png","ExpType":"fullstack","Skills":["ReactJS","SSMS(SQL)","SSIS","SSRS","ETL","REST APIs","Express","Agile","Client Interaction"]},

	{"JobTitle":"Software Engineer Co-op, Team Lead ","Company":"University Health Network (UHN) ","Duration":"Sept 2021 – Dec 2021","Summary":"•\tDeveloped a database frontend application using MS Access (VBA) and wrote macros to execute SQL queries, making data retrieval and data manipulation more streamline for researchers\n•\tWrote REST APIs using Python libraries enabled communication between multiple cloud platforms, automated scheduled emails, patient enrollment and synchronized user data across multiple platforms\n•\tOrganized meetings, code reviewed with co-workers and wrote documentation as Team Lead\n","Image":"\\assets\\uhnlogo.jpg","ExpType":"fullstack","Skills":["MS Access","VBAPython(numpy, pyodbc, Pandas)","REST APIs","SSMS(SQL)","Leadership"]},

	{"JobTitle":"Research Assistant Co-op ","Company":"National Research Council (NRC)","Duration":"Jan 2020 – April 2020","Summary":"•\tDesigned parallel Genetic Algorithms in R and Python to synthesize over 5000 datasets that were used to measure the reliability of machine learning tools related to cluster analysis\n•\tDesign HCI study using HTML/CSS, storing datasets on Amazon S3 and conducted experiments using AWS Mechanical Turk, understand human interpretation of Cluster Validity Indexes (CVIs)\n•\tDeveloped a fitness functions using determinants and modified distance formulas to cause discrepancies among various cluster validation statistics, with applications in dimensional reduction and VR technology \n","Image":"/assets/nrclogo.png","ExpType":"research","Skills":["R Studio"," Linear Algebra"," Statistics","Python(Plotly, Pandas, Scikit)","AWS","Journal Searching"]},

]

var projectData = [

	{ "ExpTitle": "Heuristic Usability Evaluation – torontopolice.on.ca ", "Duration": "July 2021– July 2021", "Link": "/project-pages/heuristicPolice.html", "Summary": "•\tUsed Jakob Neilson’s usability heuristics to identify over 15 usability issues on the Toronto Police department website\n•\tSuggested improvements, including UI elements such as accordion and breadcrumbs to organize information and provide status of system, and providing a low fidelity prototype of solutions\n", "AddDetails": "obamam is gey", "HoverExpand": false, "Image": ["/assets/toronto-police-icon.png",], "Skills": ["NN group heuristics", "low-fidelity mockups", "Report writing", "Presentation"] },

	// {"ExpTitle":"Heuristic Usability Evaluation – torontopolice.on.ca ","Duration":"July 2021– July 2021","Link":"/temp_projects_folder/picards.html","Summary":"•\tUsed Jakob Neilson’s usability heuristics to identify over 15 usability issues on the Toronto Police department website\n•\tSuggested improvements, including UI elements such as accordion and breadcrumbs to organize information and provide status of system, and providing a low fidelity prototype of solutions\n","AddDetails":"obamam is gey","HoverExpand":false,"Image":["/assets/ssnclogo.png","/assets/uoftlogo.png","/assets/ssnclogo.png","/assets/uoftlogo.png",""],"Skills":["NN group heuristics","low-fidelity mockups","Report writing","Presentation"]},

	{ "ExpTitle": "Fullstack - SportCred: Social media website for Sports fans ", "Duration": "Sept 2020 – Dec 2020", "Link": "https://www.youtube.com/watch?v=Ht4gptRzBFg&ab_channel=JawadAdham", "Summary": "•\tDesigned schemas for MongoDB using Mongoose and made backend REST APIs that made requests to DB server for services such as login auth and loading profile data using JavaScript, Express and Postman\n•\tDesigned and implemented Debates and Trivia game interface by developing dynamically rendered components using React and Material-UI frameworks, resulting in a gamifying user experience", "AddDetails": ` <a target="_blank" href="https://github.com/Maninder-sd/SportCred">Check out the github</a>  `, "HoverExpand": true, "Image": ["\\assets\\sportcredlogo.png", "\\project-pages\\sportcred-overview.png", "\\project-pages\\sportcred-model.png", "\\project-pages\\sportcred-view.png", "\\project-pages\\sportcred-controller.png"], "Skills": ["HTML/CSS/JS", "ReactJS", "NodeJS", "MaterialUI", "Express", "MongoDB", "Agile", "MVC", "JIRA"] }

]